Add k8s recommended labels
knative-sandbox/net-istio pull request #804
Opened 2021-11-05 18:12 UTC by psschwei

# Changes

Adds Kubernetes recommended labels to networking as discussed in https://github.com/knative/networking/issues/552

Note that changes to the labels in `vendor/knative.dev/networking` should be handled by the automation once https://github.com/knative/networking/pull/555 merges. 

/kind enhancement

2021-11-09 01:52 UTC, dprotaso requested changes
likewise - call it `net-istio` vs. `istio`

2021-11-09 17:48 UTC, dprotaso commented
/lgtm
/approve
/retest

2021-11-09 18:24 UTC, psschwei commented
/retest

2021-11-09 19:49 UTC, dprotaso commented
@nak3 I don't see anything in the PR that would start causing things to fail.

The one difference to when an earlier revision was passing was it used GKE 1.20 - but all the new failures are GKE 1.21

2021-11-12 05:16 UTC, nak3 commented
/retest

Yeah :cry: The CI is unstable but I believe infra side issue.

2021-11-12 05:57 UTC, merged